import assert, { deepEqual } from "node:assert";
import fs from "node:fs";
import { describe, it } from "node:test";
import * as x509 from "@peculiar/x509";
import { Bytes, BytesBlob } from "@typeberry/bytes";
import { ed25519 } from "@typeberry/crypto";
import { Result } from "@typeberry/utils";
import {
  VerifyCertError,
  altName,
  ed25519AsJsonWebKeyPair,
  generateCertificate,
  verifyCertificate,
} from "./certificate";

// taken from jamcha.in
// currently invalid, due to altname encoding mismatch.
const ALICE_CERT = fs.readFileSync("./fixtures/alice-imported.cert.pem", "utf8").trim();
const BOB_CERT = fs.readFileSync("./fixtures/bob-generated.cert.pem", "utf8").trim();

const ALICE_PAIR = ed25519.privateKey(Bytes.fill(ed25519.ED25519_PRIV_KEY_BYTES, 0).asOpaque());
const BOB_PAIR = ed25519.privateKey(Bytes.fill(ed25519.ED25519_PRIV_KEY_BYTES, 1).asOpaque());

describe("altName", async () => {
  const alice = await ALICE_PAIR;
  const keyPair = ed25519AsJsonWebKeyPair(alice);

  const aliceAltName = altName(keyPair.publicKey);

  assert.strictEqual(aliceAltName, "e3r2oc62zwfj3crnuifuvsxvbtlzetk4o5qyhetkhagsc2fgl2oka");
});

describe("X509 Certificate", () => {
  it("should generate cert", async () => {
    const ed25519Pair = await BOB_PAIR;
    const keyPair = ed25519AsJsonWebKeyPair(ed25519Pair);

    const cert = await generateCertificate({
      certId: BytesBlob.blobFromString("QUIC Networking"),
      subjectKeyPair: keyPair,
      issuerKeyPair: keyPair,
      now: new Date("2025-05-03 11:00:00"),
    });

    const altName = cert.getExtension(x509.SubjectAlternativeNameExtension);

    // make sure the alternative name is correct
    assert.strictEqual(
      altName?.toString(),
      "Subject Alternative Name:\n" + "  DNS: ekech6otoji4lz6lk3olyd5wlstspwe4x5affrnm6udcda26bpdxa",
    );

    // check the whole certificate
    assert.deepStrictEqual(cert.toString(), BOB_CERT);
  });

  it("should validate certificate generated by openssl", async () => {
    const cert = new x509.X509Certificate(ALICE_CERT);
    const certDer = new Uint8Array(cert.rawData);
    // const alicePair = await ALICE_PAIR;

    // when
    const verificationResult = await verifyCertificate([certDer]);

    // then
    deepEqual(verificationResult, Result.error(VerifyCertError.AltNameMismatch));
  });
});
