language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true
  labeling_instructions: []
  path_filters: []
  path_instructions:
    - path: 'bin/lib/index.ts'
      instructions: |
        Every new `export * as <name>` statement must have a corresponding entry point file
        at `bin/lib/exports/<name>.ts` that re-exports the package (e.g., `export * from "@typeberry/<package>"`).
        The builder will automatically detect these files and generate the appropriate exports.
    - path: 'packages/**/package.json'
      instructions: |
        Whenever a new package is added, the `packages/README.md` should be updated accordingly.
    - path: 'packages/**/package.json'
      instructions: |
        Dependencies coming from the workspace (typically the ones starting with `@typeberry/`)
        must use `*` as version.
    - path: 'packages/core/**/*.ts'
      instructions: |
        Core packages must not import any JAM-related packages
        (i.e. packages defined under `packages/jam/**`)
    - path: '**/*.ts'
      instructions: |
        rules from `./CODESTYLE.md` should be adhered to.
    - path: '**/*.ts'
      instructions: |
        Any function whose documentation mention it must not be used in production code,
        can be safely used in `*.test.ts` files. Other usage should be carefuly reviewed
        and the comment must explain why it's safe to use there.
    - path: '**/*.ts'
      instructions: |
        `as` conversions must not be used. Suggest using `tryAs` conversion methods.
    - path: '**/*.ts'
      instructions: |
        Classes with `static Codec` field must have private constructor and static `create` method.
    - path: '**/*.ts'
      instructions: |
        Casting a `bigint` (or `U64`) using `Number(x)` must have an explanation comment why
        it is safe.
    - path: '**/*.ts'
      instructions: |
        When making changes to code with comments containing links (in classes, constants, methods, etc.)
        to graypaper.fluffylabs.dev, ensure those links point to the current version for this update.
    - path: 'package.json'
      instructions: |
        When the package version changes all deprecated code scheduled for removal at that version (marked using `@deprecated` comments) should also be removed.
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  finishing_touches:
    docstrings:
      enabled: false
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 120000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
chat:
  auto_reply: true
  create_issues: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
code_generation:
  docstrings:
    language: en-US
    path_instructions: []
