export enum DisputesErrorCode {
  AlreadyJudged = "already_judged",
  BadVoteSplit = "bad_vote_split",
  VerdictsNotSortedUnique = "verdicts_not_sorted_unique",
  JudgementsNotSortedUnique = "judgements_not_sorted_unique",
  CulpritsNotSortedUnique = "culprits_not_sorted_unique",
  FaultsNotSortedUnique = "faults_not_sorted_unique",
  NotEnoughCulprits = "not_enough_culprits",
  NotEnoughFaults = "not_enough_faults",
  CulpritsVerdictNotBad = "culprits_verdict_not_bad",
  FaultVerdictWrong = "fault_verdict_wrong",
  OffenderAlreadyReported = "offender_already_reported",
  BadJudgementAge = "bad_judgement_age",
  BadValidatorIndex = "bad_validator_index",
  BadSignature = "bad_signature",
  BadGuarantorKey = "bad_guarantor_key",
  BadAuditorKey = "bad_auditor_key",
}
