# Run all benchmarks and compare the results.

name: Benchmarks

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  benchmarks:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Delete previous comment on PR
        # Don't attempt to comment if PR is coming from a fork.
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          mode: delete
          comment-tag: benchmarks
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Benchmarks run
        run: npm start -w @typeberry/benchmark
      - name: Display results
        if: always()
        run: cat ./dist/benchmarks/results.txt
      - name: Comment PR
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ./dist/benchmarks/results.txt
          comment-tag: benchmarks
      - name: Upload new transaction log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./benchmarks/*/output
            ./dist/benchmarks/results.json
            ./dist/benchmarks/results.txt
          name: benchmark-results
