# This workflow will upload the hash of every commit merged to the main branch to a public blockchain

name: Upload commit hashes to a public blockchain

on: push
  # on:
  # push:
  # branches: ["main"]

env:
  LOG_FILENAME: blockchain-git-log.json

jobs:
  blockchain-git-log:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Download previous transaction log
        uses: dawidd6/action-download-artifact@v6
        with:
          name: log
          search_artifacts: true
          branch: ${{ github.ref_name }}
        continue-on-error: true
      - run: npm run blockchain-git-log
        env:
          COMMIT_KEY_SECRET: ${{ secrets.COMMIT_KEY_SECRET }}
      - name: Upload new transaction log
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.LOG_FILENAME }}
          name: log
