name: Build - Lint & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.12
      - run: bun install --frozen-lockfile
      - run: bun run qa
      - run: bun test
      - run: GP_VERSION=0.7.1 bun test
      - run: GP_VERSION=0.7.2 bun test
      - run: bun run docs
