name: Publish @typeberry/jam to NPM

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  publish-jam:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm ci
    - name: Build Typeberry library
      run: npm run build -w @typeberry/jam
    - name: Publish package
      working-directory: ./dist/jam
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public
