name: Publish Trie package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: [
      'tools/builder/**',
      'packages/trie/**',
      'packages/bytes/**',
      '.github/workflows/publish-trie.yml'
    ]
jobs:
  publish-trie:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm ci
    - name: Get commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build Trie
      run: npm run build-trie
    - name: Generate package.json
      working-directory: ./dist/trie
      run: |
        echo '{
          "name": "@typeberry/trie",
          "version": "0.0.1-${{ env.COMMIT_HASH }}",
          "main": "trie.js",
          "author": "Fluffy Labs",
          "license": "MPL-2.0"
        }' > package.json
    - name: Publish package
      working-directory: ./dist/trie
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public
