name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Check whether package-lock.json is up to date
      run: |
        npm install --package-lock-only
        if ! git diff --quiet -- package-lock.json; then
          echo "package-lock.json is out of sync with package.json."
          echo "Please run 'npm install' and commit the updated package-lock.json."
          exit 1
        else
          echo "package-lock.json is up to date."
        fi
    - run: npm run build
    - run: npm run build -w @typeberry/lib

  npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Build distributable npm package.
      run: ./tools/build-for-npm.sh
    - run: |
        cd dist
        npm install
        node index.js --help


