name: Lint & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run qa
    - run: npm test
    - run: GP_VERSION=0.6.4 npm test
    - run: GP_VERSION=0.6.5 npm test
    - run: GP_VERSION=0.6.6 npm test
    - run: GP_VERSION=0.6.7 npm test
    - run: GP_VERSION=0.7.0 npm test
    - run: GP_VERSION=0.7.1 npm test
