name: Run JAM test vectors

on:
  pull_request_target:
    branches: ["main"]
    paths: ['.github/workflows/test-runner.yml', 'bin/test-runner/**']
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch the fork's code securely
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout JAM test vectors
        uses: actions/checkout@v4
        with:
          repository: FluffyLabs/jamtestvectors
          path: "./jamtestvectors"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run report -w @typeberry/test-runner
      - name: Display results
        if: always()
        run: cat ./dist/jamtestvectors.txt
      - name: Comment PR
        if: always() && github.event_name == 'pull_request_target'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./dist/jamtestvectors.txt
          comment_tag: jamtestvectors
      - name: Upload new transaction log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/jamtestvectors.txt
          name: jamtestvectors-results
