name: jamduna test vectors 0.6.7

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TEST_VECTORS_REF: a0c8a6a66a7f5e9cc270755498e3b811ae38bf93
  GP_VERSION: 0.6.7
  TEST_SUITE: jamduna

jobs:
  state_transition:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Checkout JAM test vectors
        uses: actions/checkout@v4
        with:
          repository: fluffylabs/test-vectors
          path: "./test-vectors"
          ref: ${{ env.TEST_VECTORS_REF }}
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm start -w @typeberry/test-runner -- jamduna-067.ts
      - name: Display results
        if: always()
        run: cat ./dist/jamduna-067.txt
      - name: Upload new results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/jamduna-067.txt
          name: jamdunavectors-results
