name: w3f test vectors

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '3 2 * * *'

jobs:
  run:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Delete previous comment on PR
        # Don't attempt to comment if PR is coming from a fork.
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          mode: delete
          comment-tag: jamtestvectors
      - uses: actions/checkout@v4
      - name: Checkout JAM test vectors
        uses: actions/checkout@v4
        with:
          repository: FluffyLabs/jamtestvectors
          path: "./jamtestvectors"
          ref: b35f63972b7abfc16f8fb41c6af59668541dab2c
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm start -w @typeberry/test-runner w3f
      - name: Display results
        if: always()
        run: cat ./dist/jamtestvectors.txt
      - name: Comment PR
        # Don't attempt to comment if PR is coming from a fork.
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ./dist/jamtestvectors.txt
          comment-tag: jamtestvectors
      - name: Upload new transaction log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/jamtestvectors.txt
          name: jamtestvectors-results
