name: Run jamduna JAM test vectors

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '3 3 * * *'

jobs:
  run:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Delete previous comment on PR
        # Don't attempt to comment if PR is coming from a fork.
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          mode: delete
          comment-tag: jamdunavectors
      - uses: actions/checkout@v4
      - name: Checkout JAM test vectors
        uses: actions/checkout@v4
        with:
          repository: jam-duna/jamtestnet
          path: "./jamdunavectors"
          ref: 6d41bb2e8f4d60dc1806df42401363b54f956c0a
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm start -w @typeberry/test-runner jamduna
      - name: Display results
        if: always()
        run: cat ./dist/jamdunavectors.txt
      - name: Comment PR
        # Don't attempt to comment if PR is coming from a fork.
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ./dist/jamdunavectors.txt
          comment-tag: jamdunavectors
      - name: Upload new results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/jamdunavectors
          name: jamdunavectors-results
