name: jamduna test vectors 0.6.5

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  TEST_VECTORS_REF: ffffffffffffffffffffffffffffffffffffffff # it is loaded in scripts/load-test-ref.sh
  GP_VERSION: 0.6.5
  TEST_SUITE: jamduna

jobs:
  state_transition:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Load test ref
        run: .github/scripts/load-test-ref.sh
      - name: Checkout JAM test vectors
        uses: actions/checkout@v4
        with:
          repository: fluffylabs/test-vectors
          path: "./test-vectors"
          ref: ${{ env.TEST_VECTORS_REF }}
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm start -w @typeberry/test-runner
      - name: Display results
        if: always()
        run: cat ./dist/jamdunavectors.txt
      - name: Upload new results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/jamdunavectors-065
          name: jamdunavectors-results
