name: davxy w3f test vectors

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  TEST_VECTORS_REF: ffffffffffffffffffffffffffffffffffffffff # loaded in scripts/load-test-ref.sh
  GP_VERSION: 0.6.7
  TEST_SUITE: w3f-davxy

jobs:
  run:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Load test ref
        run: .github/scripts/load-test-ref.sh      
      - name: Checkout JAM test vectors
        uses: actions/checkout@v4
        with:
          repository: fluffylabs/test-vectors
          path: "./test-vectors"
          ref: ${{ env.TEST_VECTORS_REF }}
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm start -w @typeberry/test-runner
      - name: Display results
        if: always()
        run: cat ./dist/w3f-davxy-067.txt
      - name: Upload new transaction log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/w3f-davxy-067.txt
          name: jamtestvectors-davxy-results
